# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0002_enemy_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='total_health',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='current_health',
            field=models.IntegerField(default=0),
        ),
    ]
