# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0004_auto_20151227_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
