# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '__first__'),
        ('enemy', '0005_auto_20151227_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemytype',
            name='drop_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.DropTable'),
        ),
    ]
