# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0006_enemytype_drop_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='enemytype',
            name='base_damage',
        ),
        migrations.AddField(
            model_name='enemy',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='dice_sides',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='number_of_dice',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='dice_sides',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='number_of_dice',
            field=models.IntegerField(default=1),
        ),
    ]
