# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0007_auto_20151230_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemytype',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
