# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20160609_0412'),
        ('enemy', '0009_auto_20160514_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemySpawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spawn_rate', models.IntegerField(default=100)),
                ('enemy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enemy.EnemyType')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_spawns', to='location.Location')),
            ],
        ),
    ]
