# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0010_enemyspawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='taunted',
            field=models.BooleanField(default=False),
        ),
    ]
