# Player Starting
BASE_HEALTH = 40
BASE_ENERGY = 20
BASE_POWER = 3
BASE_TECHNIQUE = 3
BASE_ENDURANCE = 3

HEALTH_GAINED_PER_LEVEL = 10
ENERGY_GAINED_PER_LEVEL = 5
ATTRIBUTE_POINTS_PER_LEVEL = 2

DAILY_PUNCHES = 30  # turns per reset
RESET_FREQUENCY = 24  # hours between resets

XP_BASE_AMOUNT = 1000
XP_GROWTH_PER_LEVEL = 0.2


ENEMY_IMAGE_FOLDER = "images/enemies/"
