# Player Starting
BASE_HEALTH = 40
BASE_ENERGY = 20
BASE_POWER = 3
BASE_TECHNIQUE = 3
BASE_ENDURANCE = 3

HEALTH_GAINED_PER_LEVEL = 10
ENERGY_GAINED_PER_LEVEL = 5
ATTRIBUTE_POINTS_PER_LEVEL = 2

DAILY_PUNCHES = 30  # turns per reset
RESET_FREQUENCY = 24  # hours between resets

XP_BASE_AMOUNT = 1000
XP_GROWTH_PER_LEVEL = 0.2


ENEMY_IMAGE_FOLDER = "images/enemies/"

TAUNT_SUCCESS_PERCENTAGE = 60
TAUNT_EPIC_SUCCESS_PERCENTAGE = 10

RARE_ENCOUNTER_FREQUENCY = 40
ULTRA_RARE_ENCOUNTER_FREQUENCY = 10

RELATIONSHIP_BEST_POINTS = 200
RELATIONSHIP_GOOD_POINTS = 100
RELATIONSHIP_NETURAL_POINTS = 0
RELATIONSHIP_BAD_POINTS = -100
RELATIONSHIP_HORRIBLE_POINTS = -200
