# Player Starting
BASE_HEALTH = 40
BASE_ENERGY = 20
BASE_POWER = 3
BASE_TECHNIQUE = 3
BASE_ENDURANCE = 3

HEALTH_GAINED_PER_LEVEL = 10
ENERGY_GAINED_PER_LEVEL = 5

DAILY_PUNCHES = 30

XP_BASE_AMOUNT = 100
XP_GROWTH_PER_LEVEL = 0.1
