# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20160604_2136'),
        ('location', '0002_location_starting_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.ItemType')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
        ),
    ]
