# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_locationitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationItems',
            new_name='LocationItem',
        ),
    ]
