# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '__first__'),
        ('location', '0004_auto_20160604_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='npc.NPC'),
        ),
        migrations.AlterField(
            model_name='locationitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='location.Location'),
        ),
    ]
