# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20160609_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='failure_text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='success_rate',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='service',
            name='success_text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
