# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20160609_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationservice',
            name='action_point_cost',
            field=models.IntegerField(default=0),
        ),
    ]
