# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_locationservice_action_point_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
