# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationitem',
            name='currency',
            field=models.CharField(choices=[(b'P', b'Pixels'), (b'M', b'MegaPixels')], default=b'P', max_length=1),
        ),
    ]
