# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_locationitem_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image_path', models.CharField(max_length=200)),
                ('adventure_text', models.TextField()),
                ('frequency', models.CharField(choices=[(b'COMMON', b'Common'), (b'RARE', b'Rare'), (b'ULTRA', b'Ultra Rare')], max_length=6)),
                ('location', models.ManyToManyField(blank=True, to='location.Location')),
            ],
        ),
        migrations.CreateModel(
            name='AdventureChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('success_percentage', models.IntegerField(default=100)),
                ('success_bonus', models.CharField(choices=[(b'POWR', b'power'), (b'TECH', b'technique'), (b'ENDR', b'endurance'), (b'ARMR', b'armor')], max_length=4)),
                ('success_text', models.TextField()),
                ('failure_text', models.TextField(blank=True, null=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='location.Adventure')),
                ('follow_up_adventure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='location.Adventure')),
            ],
        ),
    ]
