# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_adventure_adventurechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='image_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adventurechoice',
            name='success_bonus',
            field=models.CharField(blank=True, choices=[(b'POWR', b'power'), (b'TECH', b'technique'), (b'ENDR', b'endurance'), (b'ARMR', b'armor')], max_length=4, null=True),
        ),
    ]
