# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_auto_20160612_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='adventures', to='location.Location'),
        ),
    ]
