# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20160612_0414'),
        ('location', '0015_auto_20160612_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurechoice',
            name='energy_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventurechoice',
            name='health_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventurechoice',
            name='pixels_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventurechoice',
            name='reward_items',
            field=models.ManyToManyField(blank=True, related_name='_adventurechoice_reward_items_+', to='item.ItemType'),
        ),
        migrations.AddField(
            model_name='adventurechoice',
            name='xp_change',
            field=models.IntegerField(default=0),
        ),
    ]
