# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_playeradventure'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='adventure_rate',
            field=models.IntegerField(default=50),
        ),
    ]
