# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_location_adventure_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='page',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[(b'HEAL', b'Healing'), (b'REST', b'Rest'), (b'HEALMAX', b'Restore Health'), (b'RESTMAX', b'Restore Energy'), (b'GMB', b'Gambling'), (b'PICK4', b'Pick 4')], max_length=7),
        ),
    ]
