# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_auto_20160902_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[(b'ADV', b'Adventure'), (b'MED', b'Medical'), (b'SHP', b'Shop'), (b'PWN', b'Pawn'), (b'CAS', b'Casino'), (b'TRN', b'Training'), (b'HOM', b'Home')], max_length=3),
        ),
    ]
