# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160827_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchgame',
            name='state',
            field=models.CharField(choices=[(b'PLAY', b'Playing'), (b'WIN', b'Win'), (b'LOSE', b'Lose')], default=b'PLY', max_length=4),
        ),
    ]
