# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20160827_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchgame',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchgame',
            name='state',
            field=models.CharField(choices=[(b'PLAY', b'Playing'), (b'WIN', b'Win'), (b'LOSE', b'Lose')], default=b'PLAY', max_length=4),
        ),
    ]
