# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160828_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchgame',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='matchgame',
            name='state',
            field=models.CharField(choices=[(b'PLAY', b'Playing'), (b'OVER', b'Game Over'), (b'CLSD', b'Closed')], default=b'PLAY', max_length=4),
        ),
    ]
