# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0026_auto_20160930_0457'),
        ('game', '0005_auto_20160828_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('date_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(related_name='cheatcodes', to='player.Player')),
            ],
        ),
    ]
