# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_cheatcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatcode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheatcode',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='cheatcodes', to='player.Player'),
        ),
    ]
