# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20161026_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatcode',
            name='menu_text',
            field=models.CharField(default=' ', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheatcode',
            name='trigger_code',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
