# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20161026_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheatcode',
            old_name='trigger_code',
            new_name='cheat_class',
        ),
    ]
