# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20161026_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatcode',
            name='admin_only',
            field=models.BooleanField(default=False),
        ),
    ]
