# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_cheatcode_admin_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatcode',
            name='show_on_menu',
            field=models.BooleanField(default=True),
        ),
    ]
