# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('punches', models.IntegerField(default=0)),
                ('total_health', models.IntegerField(default=1)),
                ('current_health', models.IntegerField(default=1)),
                ('damage', models.IntegerField(default=1)),
                ('date_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('date_updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('date_last_login', models.DateTimeField(blank=True, null=True)),
                ('date_last_punch_reset', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
