# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0002_auto_20151226_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('date_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('date_updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('minimum_damage', models.IntegerField(default=0)),
                ('maximum_damage', models.IntegerField(default=1)),
                ('fail_percentage', models.IntegerField(default=0)),
                ('critial_percentage', models.IntegerField(default=0)),
                ('energy_cost', models.IntegerField(default=0)),
                ('date_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('date_updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
        ),
    ]
