# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_playerskill_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerskill',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='playerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.Skill'),
        ),
    ]
