# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20151226_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='damage',
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[(b'p', b'Passive'), (b'c', b'Combat'), (b'v', b'Victory')], default=b'p', max_length=1),
        ),
    ]
