# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20151228_0220'),
        ('player', '0005_auto_20151227_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gloves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.Item'),
        ),
        migrations.AddField(
            model_name='player',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.Item'),
        ),
    ]
