# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20160101_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
