# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
