# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20160103_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=1),
        ),
    ]
