# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_auto_20160106_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=1),
        ),
        migrations.AddField(
            model_name='avatar',
            name='name',
            field=models.CharField(default='name', max_length=20),
            preserve_default=False,
        ),
    ]
