# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_auto_20160110_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerskill',
            name='remaining_for_level_up',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skill',
            name='gained_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
