# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_auto_20160506_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pixels',
            field=models.IntegerField(default=0),
        ),
    ]
