# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0018_player_pixels'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=1)),
                ('image_path', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('layer_type', models.CharField(choices=[(b'body', b'Body'), (b'hair', b'Hair'), (b'face', b'Face'), (b'shirt', b'Shirt')], default=b'body', max_length=5)),
                ('unlock_method', models.CharField(choices=[(b'discvr', b'Discover'), (b'purcha', b'Purchase'), (b'secret', b'Secret')], default=b'discov', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.AvatarLayer')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
