# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0019_avatarlayer_playeravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarlayer',
            name='unlock_method',
            field=models.CharField(choices=[(b'start', b'Starter'), (b'discvr', b'Discover'), (b'purcha', b'Purchase'), (b'secret', b'Secret')], default=b'discov', max_length=6),
        ),
        migrations.AlterField(
            model_name='playeravatar',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.AvatarLayer'),
        ),
        migrations.AlterField(
            model_name='playeravatar',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='player.Player'),
        ),
    ]
