# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0021_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='megapixels',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='player.Player'),
        ),
    ]
