# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0022_auto_20160612_0106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playeravatar',
            unique_together=set([('player', 'layer')]),
        ),
    ]
