# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_auto_20160909_0012'),
        ('player', '0024_auto_20160906_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playercollection',
            name='found_items',
            field=models.ManyToManyField(blank=True, related_name='_playercollection_found_items_+', to='item.ItemType'),
        ),
        migrations.AddField(
            model_name='playercollection',
            name='reward_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playercollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='player.Collection'),
        ),
        migrations.AlterField(
            model_name='playercollection',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='player.Player'),
        ),
    ]
