# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0025_auto_20160909_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatusEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_turns', models.IntegerField(default=0)),
                ('date_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('date_updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='player.Player')),
            ],
        ),
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('primary_effect_type', models.CharField(choices=[(b'HP', b'Health'), (b'ENE', b'Energy'), (b'DAM', b'Damage'), (b'XP', b'Experience'), (b'PIX', b'Pixels'), (b'ARM', b'Armor'), (b'ATT', b'Attack'), (b'POW', b'Power'), (b'TEC', b'Technique'), (b'END', b'Endurance')], max_length=3)),
                ('primary_effect_amount', models.IntegerField(default=0)),
                ('secondary_effect_type', models.CharField(blank=True, choices=[(b'HP', b'Health'), (b'ENE', b'Energy'), (b'DAM', b'Damage'), (b'XP', b'Experience'), (b'PIX', b'Pixels'), (b'ARM', b'Armor'), (b'ATT', b'Attack'), (b'POW', b'Power'), (b'TEC', b'Technique'), (b'END', b'Endurance')], max_length=3, null=True)),
                ('secondary_effect_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='playerstatuseffect',
            name='status_effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.StatusEffect'),
        ),
        migrations.AlterUniqueTogether(
            name='playerstatuseffect',
            unique_together=set([('player', 'status_effect')]),
        ),
    ]
