# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0003_npcavatar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='current_energy',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='current_health',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='total_energy',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='npc',
            name='total_health',
            field=models.IntegerField(default=10),
        ),
    ]
