# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0023_auto_20160612_1804'),
        ('npc', '0005_response_responsetrigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('relationship_type', models.CharField(choices=[(b'RIVL', b'Rival'), (b'FRND', b'Friend'), (b'CUST', b'Customer'), (b'ROMC', b'Romantic')], max_length=4)),
                ('relationship_level', models.CharField(choices=[(b'BS', b'Best'), (b'GD', b'Good'), (b'NT', b'Netural'), (b'BD', b'Bad'), (b'HR', b'Horrible')], default=b'NT', max_length=4)),
                ('current_health', models.IntegerField(default=10)),
                ('current_energy', models.IntegerField(default=10)),
                ('pixels', models.IntegerField(default=0)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='npc.NPCAvatar')),
            ],
        ),
        migrations.RemoveField(
            model_name='npc',
            name='current_energy',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='current_health',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='pixels',
        ),
        migrations.AddField(
            model_name='npc',
            name='default_relationship_type',
            field=models.CharField(choices=[(b'RIVL', b'Rival'), (b'FRND', b'Friend'), (b'CUST', b'Customer'), (b'ROMC', b'Romantic')], default=b'CUST', max_length=4),
        ),
        migrations.AlterField(
            model_name='responsetrigger',
            name='trigger_type',
            field=models.CharField(choices=[(b'ASK', b'Ask about'), (b'TELL', b'Tell about'), (b'ACK', b'Acknowledge')], max_length=4),
        ),
        migrations.AddField(
            model_name='npcrelationship',
            name='npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='npc.NPC'),
        ),
        migrations.AddField(
            model_name='npcrelationship',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='player.Player'),
        ),
    ]
