# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0006_auto_20160713_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='relationship_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='responsetrigger',
            name='trigger_type',
            field=models.CharField(choices=[(b'ASK', b'Ask about'), (b'TELL', b'Tell about'), (b'ACK', b'Acknowledge'), (b'GRT', b'Greeting')], max_length=4),
        ),
    ]
