# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_container_description'),
        ('player', '0023_auto_20160612_1804'),
        ('npc', '0007_auto_20160717_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.Player')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='level_requirement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='required_items',
            field=models.ManyToManyField(blank=True, related_name='_response_required_items_+', to='item.ItemType'),
        ),
        migrations.AddField(
            model_name='responselog',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='npc.Response'),
        ),
        migrations.AddField(
            model_name='responselog',
            name='response_trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='npc.ResponseTrigger'),
        ),
    ]
