# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0008_auto_20160807_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsetrigger',
            name='response',
        ),
        migrations.AddField(
            model_name='responsetrigger',
            name='response',
            field=models.ManyToManyField(related_name='triggers', to='npc.Response'),
        ),
    ]
