# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0009_auto_20160827_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsetrigger',
            old_name='response',
            new_name='responses',
        ),
    ]
