# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0010_auto_20160827_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetrigger',
            name='response_handler',
            field=models.CharField(choices=[(b'RND', b'Random'), (b'ORD', b'Ordered')], default=b'RND', max_length=3),
        ),
    ]
