# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtype',
            old_name='curret_health_bonus',
            new_name='current_health_bonus',
        ),
        migrations.AlterField(
            model_name='item',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='player.Player'),
        ),
    ]
