# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20160103_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='player.Player'),
        ),
    ]
