# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_itemtype_armor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='level_requirement',
            field=models.IntegerField(default=1),
        ),
    ]
