# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20160106_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.ItemType')),
            ],
        ),
    ]
