# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_levelequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
