# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_itemtype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='droptable',
            name='recommended_level',
            field=models.IntegerField(default=1),
        ),
    ]
