# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_droptable_recommended_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='droptable',
            name='max_drops',
            field=models.IntegerField(default=1),
        ),
    ]
