# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_droptable_max_drops'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='combat_usable',
            field=models.BooleanField(default=False),
        ),
    ]
