# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0023_auto_20160612_1804'),
        ('location', '0018_location_adventure_rate'),
        ('item', '0014_auto_20160612_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='location.Location')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_containers', to='item.Container')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.Player')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='item.PlayerContainer'),
        ),
    ]
