# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20160623_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='action',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
