# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20160623_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
