# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_container_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playercontainer',
            unique_together=set([('container', 'player')]),
        ),
    ]
