# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_auto_20160906_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='base_type',
            field=models.CharField(choices=[(b'WEA', b'Weapon'), (b'ARM', b'Armor'), (b'CON', b'Consumable'), (b'UNL', b'Unlock'), (b'JNK', b'Junk')], max_length=3),
        ),
    ]
