# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_auto_20160909_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='sellable',
            field=models.BooleanField(default=True),
        ),
    ]
